### ISSUE TITLE
Java 21 pattern match compatibility?

### ISSUE THREAD

**Issue by peterstorm** [jbock-java/either#1]
Hello!

Does this package work with Java 21 pattern match?

Specifically de structuring the values inside the `Right` or `Left`, and of course the compiler help if you haven't handled both cases.

**Comment by deividrvale** [comment]
Hi @peterstorm so I have a basic implementation of either that indeed uses pattern matching.

[https://github.com/hezzel/cora/blob/231bc93c5766ab6aa8a33197676199d7654bbc1d/app/src/main/java/charlie/util/either/Either.java](url)

Notice that it is quite new, so i didn't implement everything nor documented everything yet. I will add it as a standalone library later.
Feel free to take a look and if you need specific functionality you can tell me. Some time next week I will make this implementation a standalone library, since Either types are quite nice :)

**Comment by peterstorm** [comment]
We ended up making our own as well, I'll probably opensource it at some point, see how it holds up to scrutiny :)
